import { readFile } from 'node:fs/promises';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const json=value=>JSON.stringify(value).replaceAll('<','\\u003c').replaceAll('\u2028','\\u2028').replaceAll('\u2029','\\u2029');
const uri=s=>'data:text/javascript;base64,'+Buffer.from(s).toString('base64');

export async function buildHypothesisViewer(experiment,images,assetRoot=new URL('../../../vendor/parts-lab/dist/vendor/',import.meta.url)) {
  // Path from scripts/atlas/experimental -> repository root is three levels.
  const [core,three,orbit]=await Promise.all(['three.core.js','three.module.js','OrbitControls.js'].map(f=>readFile(new URL(f,assetRoot),'utf8')));
  const imports={imports:{'atlas-core':uri(core),'atlas-three':uri(three.replaceAll('./three.core.js','atlas-core')),
    'atlas-orbit':uri(orbit.replaceAll('./three.module.js','atlas-three'))}};
  return `<!doctype html><html lang="ja"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>${esc(experiment.name)} / 3D配置の仮説実験</title>
<style>*{box-sizing:border-box}body{margin:0;background:#f4f6f8;color:#18252c;font:16px system-ui,sans-serif}header,main{max-width:1120px;margin:auto;padding:20px}h1{font-size:23px;margin:8px 0}h2{font-size:18px}p{line-height:1.7}.notice{padding:14px;background:#fff1cb;border-left:4px solid #9b5a00}.panel{padding:16px;background:white;border-radius:14px;margin:15px 0}button,select{font:inherit;min-height:44px;padding:8px 12px;border:1px solid #b8c4ca;border-radius:8px;background:white;color:#18252c;cursor:pointer}button[aria-pressed=true]{background:#184d5c;color:white}button:disabled{opacity:.45;cursor:default}.modes{display:flex;gap:8px;flex-wrap:wrap}#scene{height:400px;width:100%;margin:14px 0;background:#e8edf0;border-radius:12px;touch-action:none}canvas{display:block}#diagram{width:100%;height:auto;max-height:700px;border:1px solid #d2dce1}table{border-collapse:collapse;font-size:14px;width:100%}td,th{padding:10px;text-align:left;border-bottom:1px solid #dce4e8}.scroll{overflow:auto}.muted{color:#56666e}#selection{min-height:26px;font-weight:700}.selected{background:#fff1cb}.grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}@media(max-width:760px){.grid{display:block}#scene{height:340px}header,main{padding:12px}}</style>
<header><div class="muted">Codex提案 / 実験専用 / ${esc(experiment.version)}</div><h1>${esc(experiment.name)}：資料座標を使う3D配置候補</h1>
<p class="notice">全形状・配置は仮説です。実物一致は未確認。資料照合済み3Dは <b>0部品</b>、工程Aは未達のままです。色や図への一致で精度を保証しません。</p>
<p id="fit-status">${experiment.status==='candidates-generated'?'領域ごとの配置候補を計算しました。視点分離の正しさは未確認です。':'配置計算を停止しました。所属不明または領域ごとの点数不足です。初期の形状仮定だけを表示します。'}</p><p>認識した形状仮定 ${experiment.counts.proxyParts}件 ／ 配置計算に使えた形状仮定 ${experiment.counts.constrainedProxies}件。数を5以上に増やしても、元の3D達成基準への合格にはなりません。</p></header>
<main><div class="grid"><section class="panel"><h2>3D候補を比較</h2><div class="modes" id="modes"></div><div id="scene"></div><p id="state">3Dを準備しています…</p><p id="selection">図または部品を選んでください</p><p class="muted">近側／遠側は仮定したカメラの視線上の配置幅です。実際の奥行き範囲や統計的な信頼区間ではありません。回転・拡大は可能ですが修理判断には使えません。</p></section>
<section class="panel"><h2>資料の点と再投影を比較</h2><select id="view" aria-label="図のグループ"></select><p id="metric"></p><svg id="diagram" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="資料位置と投影位置の比較"></svg><p class="muted">橙の丸：資料の引出線から得た点。青の十字：計算した位置を図へ戻した点。グループ分割、カメラ、指し先＝部品中心という扱いも仮説です。</p></section></div>
<section class="panel"><h2>機種専用の手直しをせずに確認する項目</h2><p>図を複数の視点に正しく分けられたか／引出線の指し先は正しいか／名称と形状の仮定は合うか／左右や前後が逆ではないか／形状が重なっていないか。1点を学習から外した予測誤差も記録します。</p><div class="scroll"><table><thead><tr><th>部品</th><th>形状の扱い</th><th>状態</th></tr></thead><tbody>${experiment.variants.fitted.map(n=>`<tr data-part="${esc(n.id)}"><td>${esc(n.name)}</td><td>カテゴリ共通の概略形状</td><td>${n.fitted?'投影を使う推定':'初期の仮定のみ'}</td></tr>`).join('')}${experiment.excluded.map(n=>`<tr><td>${esc(n.name)}</td><td>3Dを生成しない</td><td>${esc(n.reason)}</td></tr>`).join('')}</tbody></table></div></section>
<footer class="muted">描画：Three.js / OrbitControls (MIT)。同梱ライセンスを維持。外部CDN・有料APIへの通信なし。元の2Dビューアは別ファイルで保持します。</footer></main>
<script type="application/json" id="experiment">${json(experiment)}</script><script type="application/json" id="images">${json(images)}</script>
<script>
const E=JSON.parse(document.getElementById('experiment').textContent),IM=JSON.parse(document.getElementById('images').textContent);
let activeMode=E.status==='candidates-generated'?'fitted':'prior',activePart=null;const labels={existing:'現在の生成結果',prior:'形状の初期仮定',fitted:'資料に寄せた候補',depthNear:'奥行き・近側',depthFar:'奥行き・遠側'};
for(const key of Object.keys(labels)){if(!E.variants[key])continue;const b=document.createElement('button');b.textContent=labels[key];b.dataset.mode=key;if(E.status!=='candidates-generated'&&['fitted','depthNear','depthFar'].includes(key))b.disabled=true;b.setAttribute('aria-pressed',key===activeMode);b.onclick=()=>{activeMode=key;document.querySelectorAll('[data-mode]').forEach(el=>el.setAttribute('aria-pressed',el.dataset.mode===key));window.dispatchEvent(new CustomEvent('atlas-mode',{detail:key}));drawDiagram()};document.getElementById('modes').append(b)}
window.selectAtlasPart=id=>{activePart=id;const n=E.variants.fitted.find(n=>n.id===id);document.getElementById('selection').textContent=n?n.name+' / 形状・位置は仮説':'既存モデルの部品';document.querySelectorAll('[data-part]').forEach(row=>row.classList.toggle('selected',row.dataset.part===id));window.dispatchEvent(new CustomEvent('atlas-select',{detail:id}));drawDiagram()};
document.querySelectorAll('tr[data-part]').forEach(row=>row.onclick=()=>window.selectAtlasPart(row.dataset.part));
const ns='http://www.w3.org/2000/svg',svg=document.getElementById('diagram'),choose=document.getElementById('view');
E.views.forEach((v,i)=>{const o=document.createElement('option');o.value=i;o.textContent=v.id+' / '+(v.regionId||'未分離')+' / '+v.count+'点';choose.append(o)});choose.onchange=drawDiagram;
function element(tag,attrs){const e=document.createElementNS(ns,tag);for(const[k,v]of Object.entries(attrs))e.setAttribute(k,v);return e}
function drawDiagram(){svg.replaceChildren();const v=E.views[Number(choose.value)||0];if(!v){document.getElementById('metric').textContent='使える図の点がありません';return}const im=IM[v.figureKey],size=JSON.parse(v.figureKey).slice(-2);svg.setAttribute('viewBox','0 0 '+size.join(' '));if(im)svg.append(element('image',{href:im,width:size[0],height:size[1]}));if(v.regionBounds){const[x0,y0,x1,y1]=v.regionBounds;svg.append(element('rect',{x:x0,y:y0,width:x1-x0,height:y1-y0,fill:'none',stroke:'#087f8c','stroke-width':Math.max(...size)/400}))}
document.getElementById('metric').textContent=v.status!=='candidate'?'5点未満またはカメラ仮定を解けません': '図への誤差：'+v.trainingRmseBeforePx.toFixed(1)+' → '+v.trainingRmseAfterPx.toFixed(1)+' px / 1点を外した予測：'+(v.leaveOneOutRmsePx===null?'未計算':v.leaveOneOutRmsePx.toFixed(1)+' px');
const r=Math.max(...size)/90;for(const p of v.correspondences||[]){const group=element('g',{}),xy=activeMode==='prior'?p.priorXY:p.fittedXY;if(activeMode!=='existing'&&xy)group.append(element('line',{x1:p.sourceXY[0],y1:p.sourceXY[1],x2:xy[0],y2:xy[1],stroke:'#007a9c','stroke-width':r/5}));const c=element('circle',{cx:p.sourceXY[0],cy:p.sourceXY[1],r,fill:p.id===activePart?'#ff2244':'#d47c00',opacity:.85});c.onclick=()=>window.selectAtlasPart(p.id);group.append(c);const text=element('text',{x:xy?.[0]??0,y:xy?.[1]??0,fill:'#005bba','font-size':r*3,'text-anchor':'middle','dominant-baseline':'central'});text.textContent='+';if(activeMode!=='existing'&&xy)group.append(text);svg.append(group)}}
drawDiagram();setTimeout(()=>{if(!window.__atlas3dReady)document.getElementById('state').textContent='3Dを開始できません。図・数値・元の2Dビューアは引き続き確認できます。'},7000);
</script><script type="importmap">${json(imports)}</script>
<script type="module">
import * as T from 'atlas-three';import{OrbitControls}from'atlas-orbit';
const E=JSON.parse(document.getElementById('experiment').textContent),box=document.getElementById('scene');
try{const scene=new T.Scene();scene.background=new T.Color(0xe8edf0);const[L,W,H]=E.dimensionsMm.map(x=>x/1000),diag=Math.hypot(L,W,H);
const camera=new T.PerspectiveCamera(40,1,.001,diag*100);camera.position.set(diag,diag*.9,diag);const renderer=new T.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));box.append(renderer.domElement);
const orbit=new OrbitControls(camera,renderer.domElement);orbit.target.set(0,H/2,0);orbit.update();scene.add(new T.HemisphereLight(0xffffff,0x48505a,2));const sun=new T.DirectionalLight(0xffffff,3);sun.position.set(2,4,3);scene.add(sun);
const frame=new T.LineSegments(new T.EdgesGeometry(new T.BoxGeometry(L,H,W)),new T.LineBasicMaterial({color:0x687c88}));frame.position.y=H/2;scene.add(frame);const meshes=new Map();let group;
function show(mode){if(group){scene.remove(group);for(const m of meshes.values()){m.geometry.dispose();m.material.dispose()}meshes.clear()}group=new T.Group();for(const n of E.variants[mode]||[]){if(!n.geom)continue;const g=n.geom,geo=g.type==='cylinder'?new T.CylinderGeometry(g.size[0],g.size[0],g.size[1],20):new T.BoxGeometry(...g.size);const mat=new T.MeshStandardMaterial({color:mode==='existing'?0x829299:0x547d90,roughness:.7,transparent:true,opacity:.78});const mesh=new T.Mesh(geo,mat);if(g.axis==='z')mesh.rotation.x=Math.PI/2;mesh.position.fromArray(g.position);mesh.userData.partId=n.id;meshes.set(n.id,mesh);group.add(mesh)}scene.add(group)}
show(E.status==='candidates-generated'?'fitted':'prior');window.addEventListener('atlas-mode',e=>show(e.detail));window.addEventListener('atlas-select',e=>{for(const[id,m]of meshes)m.material.emissive.set(id===e.detail?0xbb1122:0x000000)});
const ray=new T.Raycaster();let down=null;renderer.domElement.addEventListener('pointerdown',e=>{down=[e.clientX,e.clientY]});renderer.domElement.addEventListener('pointerup',e=>{if(!down||Math.hypot(e.clientX-down[0],e.clientY-down[1])>6)return;const rect=renderer.domElement.getBoundingClientRect();ray.setFromCamera(new T.Vector2((e.clientX-rect.left)/rect.width*2-1,1-(e.clientY-rect.top)/rect.height*2),camera);const hit=ray.intersectObjects([...meshes.values()])[0];if(hit)window.selectAtlasPart(hit.object.userData.partId)});
new ResizeObserver(()=>{const w=box.clientWidth,h=box.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix()}).observe(box);renderer.setSize(box.clientWidth,box.clientHeight);camera.aspect=box.clientWidth/box.clientHeight;camera.updateProjectionMatrix();
renderer.setAnimationLoop(()=>{if(!document.hidden)renderer.render(scene,camera)});document.getElementById('state').textContent='3D候補を表示中。形状と奥行きは未確認です。';window.__atlas3dReady=true;
}catch(error){document.getElementById('state').textContent='3D初期化失敗：'+error.message;console.error(error)}
</script></html>`;
}
